version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/go:1.20.4
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          name: restore image cache
          keys:
            - md-confluence-{{ .Branch }}
            - md-confluence-
            - md-
      - run:
          name: Download and install Mark utility
          command: |
            go install github.com/kovetskiy/mark@latest
            echo `mark --version`
      - run:
          name: Convert md file(s) and send to Confluence
          command: mark -f ./*.md -u $MARK_USERNAME -p $MARK_PASSWORD -b "https://makeitdrzzle.atlassian.net/wiki/"
      - save_cache:
          key: md-confluence-{{ .Branch }}
          paths:
            - md-confluence-test/

# Orchestrate our job run sequence
workflows:
  md_convert:
    jobs:
      - build:
          context:
            - md-confluence-test
